version: '3.1'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - 3000:3000
  
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: example
        POSTGRES_DB: pictures

  adminer:
    image: adminer
    ports:
      - 8080:8080