version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 5432:5432
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: example
        POSTGRES_DB: pictures

  adminer:
    image: adminer
    ports:
      - 8080:8080